### ISSUE TITLE
Empty result set from SELECT gives error in HTML output

### ISSUE THREAD

**Issue by 0luckyluke** [saltcorn/sql#2]
When the result set from a SELECT is empty, the HTML output gives an error.

TypeError: Cannot read properties of undefined (reading 'room')
    at eval (eval at template (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/underscore/underscore-node-f-pre.js:917:14), <anonymous>:6:16)
    at template (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/underscore/underscore-node-f-pre.js:924:19)
    at Object.run (/home/saltcorn/plugin_packages/@saltcorn/sql/index.js:120:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at View.run (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/view.ts:457:14)
    at Object.view (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/page.ts:262:11)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:58:44)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:69:40)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:73:42)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:73:42)
    at traverse (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:77:3)
    at Page.run (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/page.ts:231:5)
    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/page.js:52:24

A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation.

**Comment by glutamate** [comment]
Hi @0luckyluke , I can't replicate this. Could you post SQL and HTML code that triggers this?

**Comment by 0luckyluke** [comment]
SELECT b.id AS act_id,
TO_CHAR(timezone('Europe/Brussels', b.start_date), 'HH24:MI') AS act_start, 
TO_CHAR(timezone('Europe/Brussels', b.end_date) , 'HH24:MI') AS act_end,
CASE
  WHEN (b.start_date <= current_timestamp) THEN '#ff0000'
  WHEN (b.start_date <= current_timestamp + interval '30 minutes') THEN '#ffdd00'
  ELSE '#fefefe'
END AS act_busy,
u.label_name AS act_owner, 
b.room AS room
FROM booking AS b 
LEFT JOIN users AS u 
ON b.owner = u.id
WHERE ((b.start_date >= current_timestamp AND b.end_date < (current_date + 1)) 
OR (b.end_date >= current_timestamp AND b.end_date < (current_date + 1)) 
OR (b.start_date >= current_timestamp AND b.start_date < (current_date + 1)))
ORDER BY b.start_date;

HTML:
<table style="width:100%">
  <tr>
    <th style="width:12%">From</th>
    <th style="width:12%">To</th>
    <th>Owner</th>
  </tr>
  <tr>
    <td>{{rows[0].act_start}}</td>
    <td>{{rows[0].act_end}}</td>
    <td>{{rows[0].act_owner}}</td>
  </tr>
</table>

ERROR:
TypeError: Cannot read properties of undefined (reading 'act_start')
    at eval (eval at template (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/underscore/underscore-node-f-pre.js:917:14), <anonymous>:6:16)
    at template (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/underscore/underscore-node-f-pre.js:924:19)
    at Object.run (/home/saltcorn/plugin_packages/@saltcorn/sql/index.js:120:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at View.run (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/view.ts:457:14)
    at View.run_possibly_on_page (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/view.ts:552:18)
    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/view.js:73:23

**Comment by glutamate** [comment]
This is expected to fail - `rows` is [], `rows[0]` is undefined, and reading `act_start` on undefined causes a runtime error. change to something like `{{ rows[0]?.act_start }}` and the same for the others or wrap in `{{# if(rows.length>0 }} ... {{# } }}`

**Comment by 0luckyluke** [comment]
Hi Tom,

Thanks a lot, works now.
Can you give an example of how   {{# for(const row of rows) { }} works to make a table with a variable number of rows?

**Comment by glutamate** [comment]
Something like:
```
<table>
<thead>...</thead>
 <tbody>
{{# for(const row of rows) { }}
<tr>
<td>
{{ row.act_start }}
</td>
...
</tr>
{{# } }}
 </tbody>
</table>
```

the line with row.act_start can include an JS code to format eg. `{{ new Date(row.act_start).toLocaleString... }}`

**Comment by 0luckyluke** [comment]
Hi Tom,

Thanks, works great!
Would there be a command to reload this dynamic table at a certain 
interval? (e.g. a screen for upcoming events in a room...)



Luc Depuydt

Leuzestraat 96  •  8510 Bellegem  •  Belgium
E:  ***@***.***    M:  +32 498 92 62 46


------ Oorspronkelijke bericht ------
Van "Tom Nielsen" ***@***.***>
Aan "saltcorn/sql" ***@***.***>
CC "0luckyluke" ***@***.***>; "Mention" 
***@***.***>
Datum 29/01/2024 12:35:12
Onderwerp Re: [saltcorn/sql] Empty result set from SELECT gives error in 
HTML output (Issue #2)

**Comment by glutamate** [comment]
@0luckyluke a few releases ago I introduced the sleep action that helps with this. how to get periodic reloads:

1) create a page (or work in a Show view). Drag your SQL view into this. 
2) drag an action into this page. set Action = Multi step action, Style = Run on Page Load. 
3) make the first action step a sleep for however you want to wait for page refresh
4) make the second step a navigate action, Nav Action= Reload page

**Comment by 0luckyluke** [comment]
@glutamate this works fime, although the html code field (the blue square showing time and date) is "flickering" at every reload

![Schermafbeelding 2024-02-13 104007](https://github.com/saltcorn/sql/assets/156822398/ab88f193-998d-4f60-ad2b-d9656574bd8a)

The code in this field is:

<body onload="showTime()">
<table style="text-align:center; font-family:roboto; width:100%;background-color:#0000ff;color:#ffffff">
  <tr style="height:400px;">
	<td>
     <b><div id="klok" style="width:100%;font-size:800%;"></div></b>
	</td>
  </tr>
  <tr style="height:300px;">
	<td>
     <div id="datum" style="width:100%;font-size:250%;"></div>
	</td>
  </tr>
</table>

<script>
var days = ["zondag","maandag","dinsdag","woensdag","donderdag","vrijdag","zaterdag"];
var months = ["januari","februari","maart","april","mei","juni","juli","augustus","september","oktober","november","december"];

function showTime() {
     const now = new Date();
     let tijd = addZero(now.getHours()) + ":" + addZero(now.getMinutes());
	 let dagmaand = days[now.getDay()]+ ' ' + now.getDate() + ' ' + months[now.getMonth()];
	 document.getElementById("klok").innerHTML = tijd;
	 document.getElementById("datum").innerHTML = dagmaand;
	 setTimeout(showTime, 1000);
}

function addZero(i) {
  if (i < 10) {i = "0" + i}
  return i;
}
</script>
</body>

**Comment by 0luckyluke** [comment]
Resolved by adding a UNION ALL to a default result set in the SQL definition.

**Comment by j2l** [comment]
I tried both solutions:
```
<table>
<thead></thead>
<tbody>
{{# if(rows.length>0 }}
{{# for(const row of rows) { }}
<tr>
<td>
{{ row.title }}
</td>
</tr>
{{# } }}
{{# } }}
</tbody>
</table>
```
and

```
<table>
<thead></thead>
<tbody>
{{# each rows}}
<tr>
<td>
{{ this.title }}
</td>
</tr>
{{/ each}}
</tbody>
</table>
```

but none works:
```
SyntaxError: In evaluating the interpolation 
...
 in HTML code interpolation in view sql:

Invalid or unexpected token
```

But, `{{rows[0].title}}` is working, so 🙅 Any idea?

**Comment by glutamate** [comment]
@j2l things got a bit broken. I guess we switched to interpolations at some point without really thinking about the need to loop through rows

0.6.0 introduces a new output type, HTML with handlebars, which lets you use handlebars syntax as in your first example. the HTML output type users interpolations

**Comment by j2l** [comment]
Thank you @glutamate 
I see in tests/sqlview.test.js that you added a test for #each, this is great, maybe adding one for #if would help. 
Have a great week-end!
